### PR TITLE
Fixed genmodel registration

### LINKED ISSUE #29: Registration of PathBridge meta model is missing
I noticed that there is a meta model with namespace `http://www.storydriven.org/patterns/expressions/pathbridge` that resides in the `model` folder but is not properly registered in the `plugin.xml` file.

Not registering the meta model properly, can lead to issues such as failed OCL validations as discussed in [PALLADIO-436](https://jira.palladio-simulator.com/browse/PALLADIO-436).

I suggest registering the genmodel in the `plugin.xml` file.

### PR DESCRIPTION
**Pull request by seiferma**
Attempt to fix #29

### CODE REVIEW

**Comment by seiferma** [comment]
Actually, I am not sure if the reference to the first genmodel will work actually. Because the genmodel is located in the source folder, it is possible that it is not copied to the JAR. It would be better to move the generated genmodel and ecore files to the models folder.

**Comment by snowball77** [comment]
I would also prefer to fix it to make it compliant with the normal ecore project layout...

—-
Steffen Becker
University of Stuttgart, Reliable Software Systems

Am 16.08.2019 um 09:47 schrieb Stephan Seifermann <notifications@github.com<mailto:notifications@github.com>>:


Actually, I am not sure if the reference to the first genmodel will work actually. Because the genmodel is located in the source folder, it is possible that it is not copied to the JAR. It would be better to move the generated genmodel and ecore files to the models folder.

**Comment by seiferma** [comment]
OK, I moved the PathExpressions model. If this looks correct to you, I suggest to accept the pull request.

There are much more issues in this project (e.g. outdated Xtext constructs used, most parts not build as part of the Maven build). Actually, it needs a complete makeover. Especially when switching with other projects that depend on this (such as Palladio) to a new target platform, it might be necessary to migrate code to newer frameworks.

**Comment by snowball77** [comment]
I do not see major issues with the patch, anyway it is unmaintained, but still used code. In my workspace it used to compile even under 2019.06, so it should compile also in the maven build. Why does it fail?

**Pull request merged**
